<?php

// Require WP Load First
$current_url = dirname( __FILE__ );
$wp_content_pos = strpos( $current_url, 'wp-content' );
$wp_content = substr( $current_url, 0, $wp_content_pos );
require_once( $wp_content . 'wp-load.php' );

// Revert Back to Stylesheet
ob_start ( "ob_gzhandler" );
header( "Content-type: text/css; charset: UTF-8" );

// Grab the HEX color values from theme options
$accent = of_get_option( 'accent-color' );

?>


/*-----------------------------------------------------------------
 These are dynamic accent color values generated by theme options
-----------------------------------------------------------------*/

a {
	color: <?php echo $accent; ?>;
	}

::selection { 
	background: <?php echo $accent; ?>;
	}

#header .logo a:hover {
	color: <?php echo $accent; ?>;
	}

#header #nav li a:hover,
#header #nav li.current_page_item a,
#header #nav li.current-menu-parent a,
#header #nav li.current_page_parent a {
	border-bottom-color: <?php echo $accent; ?>;
	}

#header #nav ul a:hover,
#header #nav ul ul a:hover {
	color: <?php echo $accent; ?> !important;
	}

#header #nav ul li.current-menu-item a {
	color: <?php echo $accent; ?> !important;
	}

#content article .entry-header h2.entry-title a:hover {
	border-bottom-color: <?php echo $accent; ?>;
	}

#content article .entry-header .entry-meta span a:hover {
	border-bottom-color: <?php echo $accent; ?>;
	}

#content article .entry-content a.more {
	border-bottom-color: <?php echo $accent; ?>;
	}

#content article .entry-content blockquote cite a:hover {
	border-bottom-color: <?php echo $accent; ?>;
	}

#content article.format-link .entry-link h3 a:hover {
	border-bottom-color: <?php echo $accent; ?>;
	}

#content article .entry-footer a {
	background-color: <?php echo $accent; ?>;
	}

#article-nav a:hover {
	border-bottom-color: <?php echo $accent; ?>;
	}

#author-bio .author-name a:hover {
	border-bottom-color: <?php echo $accent; ?>;
	}

#comments .comment-author cite a:hover {
	border-bottom-color: <?php echo $accent; ?>;
	}

#comments a.comment-reply-link:hover,
#comments a.comment-edit-link:hover {
	border-bottom-color: <?php echo $accent; ?>;
	}

#respond input[type="submit"] {
	background-color: <?php echo $accent; ?>;
	}

.pagination a:hover {
	border-bottom-color: <?php echo $accent; ?>;
	}

body.page-template-template-homepage-php #portfolio article .entry-link {
	border-bottom-color: <?php echo $accent; ?>;
	}

body.page-template-template-contact-php #contact-form input[type="submit"] {
	background-color: <?php echo $accent; ?>;
	}

body.single-portfolio .portfolio-meta .project-button a {
	background-color: <?php echo $accent; ?>;
	}

body.page-template-template-portfolio-sortable-php .portfolio-filter li a.active,
body.page-template-template-portfolio-sortable-php .portfolio-filter li a:hover {
	border-bottom-color: <?php echo $accent; ?>;
	}

.search-form .search-submit {
	background-color: <?php echo $accent; ?>;
	}

.mighty_social_widget a:hover {
	color: <?php echo $accent; ?>;
	}

#footer .copyright a:hover {
	border-bottom-color: <?php echo $accent; ?>;
	}

#footer li a:hover {
	border-bottom-color: <?php echo $accent; ?>;
	}

.mejs-time-current {
	background: <?php echo $accent; ?> !important;
	}

.mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-current {
	background: <?php echo $accent; ?> !important;
	}
